{
 "title": "Subreddit sentiments",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "topic", "label": "Topic", "query": { "query": "" } },
   {
    "name": "country",
    "label": "Country",
    "query": "India,USA,United Kingdom,Australia,Russia,China,Japan"
   }
  ]
 },
 "panels": [
  {
   "title": "Frequent Sentiment Keywords by Country",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "SELECT matched_keyword, sum(comment_count) AS frequency FROM reddit.topic_matched_keyword_summary WHERE topic = '$topic' AND country = '$country' AND api_timestamp > $__timeFrom AND api_timestamp < $__timeTo GROUP BY topic, matched_keyword ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Sentiment by Country (%)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "SELECT country, SUM(positive_count) * 100.0 / SUM(positive_count + negative_count + neutral_count) AS popularity, SUM(negative_count) * 100.0 / SUM(positive_count + negative_count + neutral_count) AS disliked, SUM(neutral_count) * 100.0 / SUM(positive_count + negative_count + neutral_count) AS Neutral FROM reddit.country_sentiment WHERE api_timestamp > $__timeFrom AND api_timestamp < $__timeTo AND country = '$country' AND topic = '$topic'  GROUP BY country, topic ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Positive Sentiment Intensity by Country",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "SELECT country AS label, CAST(SUM(total_positive) AS int) AS size FROM reddit.country_sentiment_summary WHERE api_timestamp > $__timeFrom AND api_timestamp < $__timeTo AND topic = '$topic' GROUP BY country ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Negative Sentiment Intensity by Country",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "SELECT country AS label, SUM(total_negative) AS size FROM reddit.country_sentiment_summary WHERE api_timestamp > $__timeFrom AND api_timestamp < $__timeTo AND topic = '$topic' GROUP BY country ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Sentiment Status Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "columnTime": "api_timestamp",
     "keyspace": "reddit",
     "table": "country_sentiment",
     "target": "SELECT country, topic, api_timestamp AS time, positive_count AS positive, negative_count AS negative, neutral_count AS neutral FROM reddit.country_sentiment WHERE topic= '${topic}'  AND country = '${country}'  AND api_timestamp > $__timeFrom AND api_timestamp < $__timeTo ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Average Sentiment Score",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "columnTime": "api_timestamp",
     "target": "SELECT country,topic, api_timestamp AS time, sentiment_score_avg AS avg_score FROM reddit.country_sentiment WHERE topic= '${topic}'  AND country = '${country}'   AND api_timestamp > $__timeFrom AND api_timestamp < $__timeTo ALLOW FILTERING;"
    }
   ]
  }
 ]
}