name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # First Docker Image
      - name: Build Docker Image cassandra
        working-directory: ./reddit-sentiment-analytics/cassandra
        run: |
          docker build -t cassandra:latest -f Dockerfile .

      - name: Tag Docker Image cassandra
        run: |
          docker tag cassandra:latest docker.io/${{ secrets.DOCKER_USERNAME }}/cassandra:latest

      - name: Push Docker Image cassandra to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/cassandra:latest

      # Second Docker Image
      - name: Build Docker Image reddit_producer
        working-directory: ./reddit-sentiment-analytics/reddit_producer
        run: |
          docker build -t reddit_producer:latest -f Dockerfile .

      - name: Tag Docker Image reddit_producer
        run: |
          docker tag reddit_producer:latest docker.io/${{ secrets.DOCKER_USERNAME }}/reddit_producer:latest

      - name: Push Docker Image reddit_producer to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/reddit_producer:latest

      # Third Docker Image
      - name: Build Docker Image spark_stream_processor
        working-directory: ./reddit-sentiment-analytics/spark
        run: |
          docker build -t spark_stream_processor:latest -f Dockerfile .

      - name: Tag Docker Image spark_stream_processor
        run: |
          docker tag spark_stream_processor:latest docker.io/${{ secrets.DOCKER_USERNAME }}/spark_stream_processor:latest

      - name: Push Docker Image spark_stream_processor to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/spark_stream_processor:latest

      # Fourth Docker Image
      - name: Build Docker Image grafana
        working-directory: ./reddit-sentiment-analytics/grafana
        run: |
          docker build -t grafana:latest -f Dockerfile .

      - name: Tag Docker Image grafana
        run: |
          docker tag grafana:latest docker.io/${{ secrets.DOCKER_USERNAME }}/grafana:latest

      - name: Push Docker Image grafana to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/grafana:latest
